services:
  - docker

language: java
jdk: openjdk14

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build

after_success:
  - docker login mangeiregistry.azurecr.io -u $DOCKER_USER -p DOCKER_PASSWORD
  - docker build -t mangeiregistry.azurecr.io/mangei/hello-kubernetes:1.0.1 .
  - docker push mangeiregistry.azurecr.io/mangei/hello-kubernetes:1.0.1
