services:
  - docker

language: java
jdk: openjdk14

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build

after_success:
  - docker login -u $DOCKER_USER -p DOCKER_PASSWORD
  - docker-compose build
  - docker tag mangeiregistry.azurecr.io/mangei/hello-kubernetes:latest mangeiregistry.azurecr.io/mangei/hello-kubernetes:$TAG
  - docker push mangeiregistry.azurecr.io/mangei/hello-kubernetes:$TAG
