apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hello-kubernetes
  name: hello-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-kubernetes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-kubernetes
    spec:
      containers:
        - image: mangeiregistry.azurecr.io/mangei/hello-kubernetes:1.0.0
          name: hello-kubernetes
          ports:
            - containerPort: 8080
